- name: image
  docker_image:
    name: "{{cadvisor_image}}"
    state: present

- name: start container
  docker_container:
    name: cadvisor
    image: "{{cadvisor_image}}"
    restart_policy: "always"
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - name: "containers"