- name: Prometheus Docker Image
  docker_image:
    name: {{prom_image}}
    state: present

- name: Copy config file
  copy:
    src: prometheus.yml
    dest: /etc/prometheus.yml

- name: Prometheus docker volume
  docker_volume:
    name: prom-data
    state: present

- name: Start prometheus container
  docker_container:
    name: prometheus
    image: {{prom_image}}
    ports:
      - "9090:9090"
    volumes:
      - "/etc/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prom-data:/prometheus-data"
    networks:
      - name: "containers"

- name: Node Exporter Docker Image
  docker_image:
    name: {{prom_node_image}}
    state: present

- name: Start Node Exporter container
  docker_container:
    name: node_exporter
    image: {{prom_node_image}}
    ports:
      - "9100:9100"
    networks:
      - name: "containers"
