- name: nzbget docker image
  docker_image:
    name: "{{nzbget_image}}"
    state: present

- name: nzbget data dir
  file:
    name: "{{base_dir}}/{{config_dir}}/nzbget"
    state: directory
    owner: media
    group: media
    mode: 0755

- name: template config file
  template:
    src: nzbget.conf.j2
    dest: "{{base_dir}}/{{config_dir}}/nzbget/nzbget.conf"

- name: Start container
  docker_container:
    name: nzbget
    image: "{{nzbget_image}}"
    restart_policy: "always"
    ports:
      - "6789:6789"
    networks:
      - name: "containers"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{base_dir}}/{{config_dir}}/nzbget:/config"
      - "{{base_dir}}/{{media_dir}}/{{downloads_dir}}:/downloads"
    env:
      PGID: "{{media_uid}}"
      PUID: "{{media_gid}}"
      TZ: "{{timezone}}"