- name: apt update
  apt:
    update_cache: yes
  when:
    - apt_update is defined
    - apt_update == True

- name: Docker dep - apt-transport-https
  apt:
    update_cache: no
    name: apt-transport-https

- name: Docker dep - ca-certificates
  apt:
    update_cache: no
    name: ca-certificates

- name: Docker dep - curl
  apt:
    update_cache: no
    name: curl

- name: Docker dep - gnupg2
  apt:
    update_cache: no
    name: gnupg2

- name: Docker dep - software-properties-common
  apt:
    update_cache: no
    name: software-properties-common

- name: Docker Key
  apt_key:
    url=https://download.docker.com/linux/debian/gpg
    state=present
    id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable" 
    state: present
    update_cache: yes

- name: Docker Package
  apt:
    update_cache: no
    name: docker-ce
