- name: Add group
  group:
    name: media
    gid: "{{ media_gid }}"
    state: present

- name: Add user
  user:
    name: media
    uid: "{{ media_uid }}"
    group: media

- name: Create tv directory
  file:
    path: "{{base_dir}}/{{media_dir}}/{{tv_dir}}"
    state: directory
    owner: media
    group: media
    mode: 0755

- name: Create movies directory
  file:
    path: "{{base_dir}}/{{media_dir}}/{{movies_dir}}"
    state: directory
    owner: media
    group: media
    mode: 0755

- name: Create downloads directory
  file:
    path: "{{base_dir}}/{{media_dir}}/{{downloads_dir}}"
    state: directory
    owner: media
    group: media
    mode: 0755
