- name: plex docker image
  docker_image:
    name: "{{plex_image}}"
    state: present

- name: plex config dir
  file:
    name: "{{base_dir}}/{{config_dir}}/plex"
    state: directory
    owner: media
    group: media
    mode: 0755

- name: plex transcode dir
  file:
    name: "{{base_dir}}/{{media_dir}}/plex_transcode"
    state: directory
    owner: media
    group: media
    mode: 0755

- name: Start container
  docker_container:
    name: plex
    image: "{{plex_image}}"
    restart_policy: "always"
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{base_dir}}/{{config_dir}}/plex:/config"
      - "{{base_dir}}/{{media_dir}}/plex_transcode:/transcode"
      - "{{base_dir}}/{{media_dir}}/{{tv_dir}}:/tv"
      - "{{base_dir}}/{{media_dir}}/{{movies_dir}}:/movies"
    env:
      PGID: "{{media_uid}}"
      PUID: "{{media_gid}}"
      TZ: "{{timezone}}"
      VERSION: "latest"
  tags:
    - plex
